In [1]:
import numpy as np

In [ ]:
Objective:
You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

🧠 Project Description:
A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

📋 Project Tasks:
**Data Creation:**Create suitable arrays to represent students, subjects, and their marks.

**Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.

**Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.

**Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.

**Data Modification:**Apply operations to update marks, remove data, or identify unique information.

**Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.

**Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data


In [2]:
#Data Creation
import numpy as np
students=np.array(["Alia", "Riya", "Ram", "Priya", "Eve", "Don"])
subjects=np.array(["Physics", "Chemistry", "English", "Maths"])
marks=np.array([
    [90, 65, 95, 91],
    [80, 75, 90, 85],
    [95, 89, 94, 87],
    [76, 64, 68, 87],
    [89, 85, 91, 85],
    [88, 71, 60, 40]])
print(students)
print(subjects)
print(marks)

['Alia' 'Riya' 'Ram' 'Priya' 'Eve' 'Don']
['Physics' 'Chemistry' 'English' 'Maths']
[[90 65 95 91]
 [80 75 90 85]
 [95 89 94 87]
 [76 64 68 87]
 [89 85 91 85]
 [88 71 60 40]]


In [3]:
#Data Exploration
print(students.ndim)
print(subjects.ndim)
print(marks.ndim)

1
1
2


In [4]:
print(students.size)
print(subjects.size)
print(marks.size)

6
4
24


In [5]:
print(students.shape)
print(subjects.shape)
print(marks.shape)

(6,)
(4,)
(6, 4)


In [6]:
#Data Transformation
print(marks.flatten())
print(marks.reshape(12,2))
print(marks.T)
print(np.flip(marks))

[90 65 95 91 80 75 90 85 95 89 94 87 76 64 68 87 89 85 91 85 88 71 60 40]
[[90 65]
 [95 91]
 [80 75]
 [90 85]
 [95 89]
 [94 87]
 [76 64]
 [68 87]
 [89 85]
 [91 85]
 [88 71]
 [60 40]]
[[90 80 95 76 89 88]
 [65 75 89 64 85 71]
 [95 90 94 68 91 60]
 [91 85 87 87 85 40]]
[[40 60 71 88]
 [85 91 85 89]
 [87 68 64 76]
 [87 94 89 95]
 [85 90 75 80]
 [91 95 65 90]]


In [7]:
#Data Combination
student = np.array(['Alia',"Riya","Ram"])
marks = np.array([[90, 65, 95, 91],
    [80, 75, 90, 85],
    [95, 89, 94, 87]])
student_1 = np.array(["Siya"])
marks_1 = np.array([[75,80,90,89]])

student = np.concatenate((student,student_1))
marks = np.concatenate((marks,marks_1))
print(student)
print(marks)

['Alia' 'Riya' 'Ram' 'Siya']
[[90 65 95 91]
 [80 75 90 85]
 [95 89 94 87]
 [75 80 90 89]]


In [8]:
marks=marks.reshape(-1)
print(marks)
np.split(marks,4)

[90 65 95 91 80 75 90 85 95 89 94 87 75 80 90 89]


[array([90, 65, 95, 91]),
 array([80, 75, 90, 85]),
 array([95, 89, 94, 87]),
 array([75, 80, 90, 89])]

In [9]:
#Data Modification
marks[4] = 40
print(marks)

[90 65 95 91 40 75 90 85 95 89 94 87 75 80 90 89]


In [10]:
c=np.delete(marks,4)
print(c)

[90 65 95 91 75 90 85 95 89 94 87 75 80 90 89]


In [11]:
print(marks)
np.unique(marks)

[90 65 95 91 40 75 90 85 95 89 94 87 75 80 90 89]


array([40, 65, 75, 80, 85, 87, 89, 90, 91, 94, 95])

In [12]:
#Data Type Handling
print(marks.dtype)
print(marks.astype(dtype=float))
print(marks.astype(dtype=str))

int64
[90. 65. 95. 91. 40. 75. 90. 85. 95. 89. 94. 87. 75. 80. 90. 89.]
['90' '65' '95' '91' '40' '75' '90' '85' '95' '89' '94' '87' '75' '80'
 '90' '89']


In [13]:
#Copy & View Behaviour
a = marks.copy()
a[0] = 99
print(a)

[99 65 95 91 40 75 90 85 95 89 94 87 75 80 90 89]


In [14]:
b = marks.view()
b[0] = 100
print(marks)

[100  65  95  91  40  75  90  85  95  89  94  87  75  80  90  89]
